version: '3.8'

services:
  node1:
    image: ubuntu:latest
    container_name: scheduler-node-1
    
  node2:
    image: ubuntu:latest
    container_name: scheduler-node-2
    
  node3:
    image: ubuntu:latest
    container_name: scheduler-node-3
